[package]
name = "edge-orchestrator"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "=4.6.7", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
edge-controller-core = { path = "../edge-controller-core" }
edge-observability = { path = "../edge-observability" }
edge-provider-cloudflare = { path = "../edge-provider-cloudflare" }
edge-provider-vultr = { path = "../edge-provider-vultr" }
edge-shared-types = { path = "../edge-shared-types" }
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "net"] }
tonic = { version = "0.14.5", features = ["tls-ring"] }
tracing = "=0.1.44"

[lib]
path = "src/lib.rs"

[[bin]]
name = "edge-orchestrator"
path = "src/main.rs"
