[package]
name = "edge-console"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "=4.6.7", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
edge-observability = { path = "../edge-observability" }
edge-local-runtime = { path = "../edge-local-runtime" }
thiserror = "=2.0.18"
tracing = "=0.1.44"
edge-shared-types = { path = "../edge-shared-types" }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.14.5"
rusqlite = { version = "0.37.0", features = ["bundled"] }

[[bin]]
name = "edge-console"
path = "src/main.rs"
